apiVersion: v1
kind: ConfigMap
metadata:
  name: minio-config
  labels:
    app: myapplication
    tier: minio
data:
  S3_BUCKET: {{ .Values.bucket }}
  MINIO_ACCESS_KEY: {{ .Values.accessKey }}
  MINIO_SECRET_KEY: {{ .Values.secret }}

