apiVersion: v1
kind: Service
metadata:
  name: minio
  labels:
    app: myapplication
    tier: minio
spec:
  ports:
    - port: 80
      targetPort: 9000
  selector:
    app: myapplication
    tier: minio

